# Generated by Django 3.0.3 on 2020-02-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='booktest.Book'),
        ),
    ]
