# Generated by Django 3.0.3 on 2020-02-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0008_article_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
